/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthorInfo: typeof import('./../theme/components/AuthorInfo.vue')['default']
    IconTool: typeof import('./../theme/components/IconTool.vue')['default']
    PageInfo: typeof import('./../theme/components/PageInfo.vue')['default']
    Sidebar: typeof import('./../theme/components/Sidebar.vue')['default']
  }
}
