export const AIData = [
  {
    src: '/ai-site/poe.png',
    title: 'Poe 机器人',
    desc: '一款集成各 AI 程序的网站（包含GPT4、Claude等）',
    link: 'https://poe.com/ChatGPT',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2022/11/notion.png',
    title: 'Notion AI',
    desc: '一款功能丰富、智能化、易用性强的人工智能工具，适用于各种内容创作者',
    link: 'https://www.notion.so',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/02/openai-avatar.png',
    title: 'ChatGPT',
    desc: '这是真人工智能，不是人工智障',
    link: 'https://chat.openai.com/',
  },
  {
    src: '/ai-site/beautiful.png',
    title: 'beautiful.ai',
    desc: '介绍适用于工作场所的生成式 AI 演示软件（PPT）',
    link: 'https://www.beautiful.ai/',
  },
  {
    src: '/ai-site/mst.png',
    title: 'mst.ai',
    desc: '一款集成各 AI 程序的网站（包含GPT4、MidJourney等）',
    link: 'https://mst.ai/tools/chat',
  },
  {
    src: '/ai-site/gamma.png',
    title: 'Gamma',
    desc: '一种由 AI 自动生成精密Idea（PPT）等，无需任何格式和设计工作即可创建精美、引人入胜的内容。',
    link: 'https://gamma.app/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/04/1679494097Stable-Diffusion.png',
    title: 'Stable Diffusion',
    desc: 'AI 绘画，输入关键字生成图片',
    link: 'https://stability.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/02/civitai-icon-filled-36.png',
    title: 'Civitai',
    desc: '训练好的模型分享网站',
    link: 'https://civitai.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/02/ppbaidu.png',
    title: '文心一格',
    desc: '百度 AI 产品，创意和艺术辅助产品',
    link: 'https://yige.baidu.com/creation',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/02/niji-journey.png',
    title: 'Nijijourney',
    desc: '魔法般的二次元绘画生成',
    link: 'https://nijijourney.com/zh/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/02/midjourney.png',
    title: 'Midjourney',
    desc: '是一款搭载在 Discord 上的人工智能绘画聊天工具',
    link: 'https://www.midjourney.com/home/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/02/TOME.png',
    title: 'Tome AI',
    desc: '由AI驱动的讲故事形式',
    link: 'https://beta.tome.app/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Character-AI.jpg',
    title: 'Character AI',
    desc: '是一个神经语言模型的聊天机器人网络应用',
    link: 'https://beta.character.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/jaster.png',
    title: 'Jasper',
    desc: '文本生成器，使用 AI 制作出令人惊叹的文案',
    link: 'https://www.jasper.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/tabnine.png',
    title: 'Tabnine',
    desc: '是一个AI代码助手',
    link: 'https://www.tabnine.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/copilot-x.png',
    title: 'Copilot X',
    desc: 'GitHub 和 OpenAI 合作开发的一个代码自动生成工具',
    link: 'https://github.com/features/preview/copilot-x',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/remove-bg.jpg',
    title: 'RemoveBG',
    desc: '图片去除背景',
    link: 'https://www.remove.bg/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/PhotoRoom.jpg',
    title: 'PhotoRoom',
    desc: '移除背景并创建产品图片',
    link: 'https://www.photoroom.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/writersonic.jpg',
    title: 'Writesonic',
    desc: '创作的最佳AI作家',
    link: 'https://writesonic.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/copy.png',
    title: 'Copy.AI',
    desc: '为企业生成高质量的文案',
    link: 'https://www.copy.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Outplay.jpg',
    title: 'Outplay',
    desc: 'AI生成销售话术',
    link: 'https://outplayhq.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/cowriter.png',
    title: 'CoWriter',
    desc: 'AI辅助写作',
    link: 'https://cowriter.org/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/ai-data-sidekick-1.jpg',
    title: 'AI Data Sidekick',
    desc: 'AI编写SQL代码',
    link: 'https://www.airops.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Fireflies.png',
    title: 'Fireflies',
    desc: '该工具可插入 Zoom、Teams 或 Webex 等流行的视频会议工具，并自动执行做笔记和创建转录的过程',
    link: 'https://fireflies.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Artbreeder.jpg',
    title: 'Artbreeder',
    desc: '是一款十分有趣的捏脸娱乐软件',
    link: 'https://www.artbreeder.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/dreamlike.jpg',
    title: 'dreamlike.art',
    desc: '在几秒钟内创造出令人惊叹的原创艺术',
    link: 'https://dreamlike.art/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/getimg.png',
    title: 'getimg.ai',
    desc: '创造出令人惊叹的头像',
    link: 'https://getimg.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/stockimg.jpg',
    title: 'stockimg',
    desc: '可帮助用户在几分钟内生成徽标、书籍封面、横幅等',
    link: 'https://stockimg.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/P.jpg',
    title: 'Phygital+',
    desc: '让创作者在没有代码的情况下使用神经网络',
    link: 'https://phygital.plus/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/arclab1.jpg',
    title: 'ARC Lab',
    desc: '腾讯ARC实验室推出的AI人像修复小工具',
    link: 'https://arc.tencent.com/zh/ai-demos/faceRestoration',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/papercup.png',
    title: 'Papercup',
    desc: '人工智能驱动的配音',
    link: 'https://www.papercup.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Voice-Mode.png',
    title: 'Voice Mode',
    desc: '免费即时变声器',
    link: 'https://www.voicemod.net/zh/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/soundraw.jpg',
    title: 'Soundraw',
    desc: '全新的AI音乐平台',
    link: 'https://soundraw.io/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/lalal.png',
    title: 'LALAL',
    desc: '提供音乐源分离服务，使用ai技术从任何音频中提取人声，伴奏和多种乐器',
    link: 'https://www.lalal.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/boomy.png',
    title: 'Boomy',
    desc: '在几秒钟内创作出原创歌曲',
    link: 'https://www.boomy.com',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/endel.jpg',
    title: 'Endel',
    desc: '个性化的声音景观',
    link: 'https://endel.io/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/murf.png',
    title: 'MURF',
    desc: '将文字输出为语音，可用于视频制作',
    link: 'https://murf.ai/%20',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/mubert.jpg',
    title: 'Mubert',
    desc: '为内容创作者、品牌和开发者提供的新的免版税音乐生态系统',
    link: 'https://mubert.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/riffusion.png',
    title: 'Riffusion',
    desc: '一个基于AI生成音乐的项目',
    link: 'https://www.riffusion.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/poly.png',
    title: 'polyAI',
    desc: '语音助手，企业智能客服语音服务',
    link: 'https://poly.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Cascadeur.jpg',
    title: 'Cascadeur',
    desc: '最简单的AI辅助关键帧动画制作软件',
    link: 'https://cascadeur.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/munch.png',
    title: 'MunchAI',
    desc: '自动将长视频转换为数据驱动的短片，用于社交媒体',
    link: 'https://www.getmunch.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/Synthesia.jpg',
    title: 'Synthesia',
    desc: '该平台提供了一个直观的界面，可以简化任何人的视频创作',
    link: 'https://www.synthesia.io',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/fliki.jpg',
    title: 'Fliki',
    desc: '用AI语音将文字变成视频',
    link: 'https://fliki.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/pollinations.jpg',
    title: 'pollinations',
    desc: '您的引擎 个性化的媒体',
    link: 'https://pollinations.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/03/autodraw-1.jpg',
    title: 'Autodraw',
    desc: '人工智能画画平台',
    link: 'https://www.autodraw.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/04/ty.png',
    title: '通义千问',
    desc: '阿里开发的大语言模型',
    link: 'https://tongyi.aliyun.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/04/googleBard.png',
    title: 'Bard',
    desc: 'Google 推出的 AI 聊天对话机器人 Bard',
    link: 'https://bard.google.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/04/1679564778Codeium.png',
    title: 'Codeium',
    desc: '人工智能编码及检索',
    link: 'https://codeium.com/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/04/1679564753CodiumAI.png',
    title: 'CodiumAI',
    desc: 'AI 代码测试工具',
    link: 'https://www.codium.ai/',
  },
  {
    src: 'https://c.runoob.com/wp-content/uploads/2023/04/Codiga.png',
    title: 'Codiga',
    desc: 'AI 代码实时分析',
    link: 'https://www.codiga.io/',
  },
]
