name: auto-generate

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: auto-generate-experience
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
  
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
            
        - name: Setup pnpm
          uses: pnpm/action-setup@v4
    
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
    
        - name: Generate
          run: npm run generate-myself
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Commit & Push
          run: |
            git config user.name wincheshe
            git config user.email 329487092@qq.com
            git add -A .
            git commit -m "generated"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v5
          with:
            title: Genrate experience in ${{ github.run_attempt }}
            token: ${{ secrets.GITHUB_TOKEN }}
            body: Generate experience
            delete-branch: true
            committer: wincheshe <winchesHe@users.noreply.github.com>