name: auto-generate

on:
  # schedule:
  #   - cron: "0 0 */3 * *"
  # workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: auto-generate-experience
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
  
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
            
        - name: Install pnpm
          run: npm install -g pnpm
    
        - name: Install dependencies
          run: pnpm install --no-frozen-lockfile
    
        - name: Generate
          run: npm run generate-myself
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Commit & Push
          run: |
            git config user.name wincheshe
            git config user.email 329487092@qq.com
            git config --local 'https://github.com/.extraheader AUTHORIZATION: basic ${{ secrets.GITHUB_TOKEN }}'
            git add -A .
            git commit -m "generated"
            git push --force-with-lease
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.repository_owner }}